package x11

var ewmhSupported = []string{
	"_NET_SUPPORTED",
	"_NET_ACTIVE_WINDOW",
	"_NET_CURRENT_DESKTOP",
	"_NET_DESKTOP_NAMES",
	"_NET_DESKTOP_VIEWPORT",
	"_NET_NUMBER_OF_DESKTOPS",
	"_NET_CLIENT_LIST",
	"_NET_WM_STRUT",
	// "_NET_WM_STRUT_PARTIAL",
}
